"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export function Footer() {
  return (
    <footer className="bg-gray-950 py-12 text-gray-300">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <Link href="/" className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 rounded-full bg-gradient-to-r from-purple-600 to-blue-600 flex items-center justify-center">
                <span className="text-white font-bold text-sm">D</span>
              </div>
              <div className="font-bold text-lg bg-clip-text text-transparent bg-gradient-to-r from-white to-blue-300">
                DreamActor-M1
              </div>
            </Link>
            <p className="text-sm text-gray-400 mt-2 mb-4">
              A cutting-edge DiT-based human animation framework with hybrid guidance for fine-grained holistic controllability, multi-scale adaptability, and long-term temporal coherence.
            </p>
            <div className="flex space-x-4">
              <Link href="https://github.com/grisoon/DreamActor-M1" target="_blank" rel="noopener noreferrer">
                <Button size="sm" variant="ghost" className="text-gray-400 hover:text-white">
                  GitHub
                </Button>
              </Link>
              <Link href="https://arxiv.org/abs/2504.01724" target="_blank" rel="noopener noreferrer">
                <Button size="sm" variant="ghost" className="text-gray-400 hover:text-white">
                  Paper
                </Button>
              </Link>
            </div>
          </div>
          
          <div>
            <h3 className="font-semibold mb-4 text-white">Navigation</h3>
            <ul className="space-y-2">
              <li>
                <Link href="/" className="text-sm hover:text-white transition-colors duration-200">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/#method" className="text-sm hover:text-white transition-colors duration-200">
                  Method
                </Link>
              </li>
              <li>
                <Link href="/#results" className="text-sm hover:text-white transition-colors duration-200">
                  Results
                </Link>
              </li>
              <li>
                <Link href="/#citation" className="text-sm hover:text-white transition-colors duration-200">
                  Citation
                </Link>
              </li>
            </ul>
          </div>
          
          <div>
            <h3 className="font-semibold mb-4 text-white">BibTeX Citation</h3>
            <Card className="bg-gray-900 border-gray-800">
              <CardContent className="pt-4 pb-2">
                <pre className="text-xs text-gray-400 overflow-x-auto">
{`@misc{luo2025dreamactorm1holisticexpressiverobust,
  title={DreamActor-M1: Holistic, Expressive and Robust 
  Human Image Animation with Hybrid Guidance}, 
  author={Yuxuan Luo and Zhengkun Rong and Lizhen Wang 
  and Longhao Zhang and Tianshu Hu and Yongming Zhu},
  year={2025},
  eprint={2504.01724},
  archivePrefix={arXiv},
  primaryClass={cs.CV},
  url={https://arxiv.org/abs/2504.01724}, 
}`}
                </pre>
              </CardContent>
            </Card>
          </div>
        </div>
        
        <Separator className="my-8 bg-gray-800" />
        
        <div className="flex flex-col md:flex-row items-center justify-between text-xs text-gray-500">
          <p>
            © {new Date().getFullYear()} DreamActor-M1 - Bytedance Intelligent Creation
          </p>
          <p className="mt-2 md:mt-0">
            The images and videos are sourced from public domains or generated by models for research purposes only.
          </p>
        </div>
      </div>
    </footer>
  );
} 